name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have any dependencies, you can install them here
        # For example, if you have a requirements.txt file, uncomment the next line
        # pip install -r requirements.txt

    - name: Run the game
      run: |
        python your_script_name.py  # Replace with the name of your Python file
